const libros = [
  { titulo: "¿Alguna duda?", autor: "Alan Martínez Vázquez", estado: "Malo" },
  { titulo: "Atlas", autor: "Estado de México", estado: "Bueno" },
  { titulo: "Albert Einstein", autor: "Titanes de la historia", estado: "Bueno" },
  { titulo: "Aladino", autor: "Tormot", estado: "Bueno" },
  { titulo: "Año 2000", autor: "Federico Gimeno Labadia y Francisco J. Sanchis Lloró.", estado: "Bueno" },
  { titulo: "Antropología", autor: "UAEM", estado: "Regular" },
  { titulo: "Atlas", autor: "Estado de México", estado: "Bueno" },
  { titulo: "Aventuras de Tom Sawyer", autor: "Mark Twain", estado: "Regular" },
  { titulo: "Barrabas y otros Relatos", autor: "Par Lagerkvist", estado: "Bueno" },
  { titulo: "Biologia", autor: "Marta Patricia Germán Cortés y Eusebio Miranda Guerrero", estado: "Regular" },
  { titulo: "Biologia 2", autor: "UAEM", estado: "Bueno" },
  { titulo: "Biologia la Ciencia de la vida", autor: "Elena de Erice y Arturo González", estado: "Bueno" },
  { titulo: "Biologia 2", autor: "UAEM", estado: "Regular" },
  { titulo: "Como Encontrar la paz", autor: "Ellien G. White", estado: "Bueno" },
  { titulo: "Código electoral", autor: "IEEM", estado: "Bueno" },
  { titulo: "Consultor temático", autor: "Editorial Reymo", estado: "Bueno" },
  { titulo: "Como en la tierra", autor: "Guillermo Alfonso García Santin", estado: "Bueno" },
  { titulo: "Como en la tierra Parte 3", autor: "Guillermo Alfonso García Santin", estado: "Bueno" },
  { titulo: "Cuentos de la selva", autor: "Horacio Quiroga", estado: "Bueno" },
  { titulo: "Cerebro y Conducta", autor: "Ucta", estado: "Bueno" },
  { titulo: "Como una novela", autor: "Daniel Pennac", estado: "Bueno" },
  { titulo: "Cálculo con geometría analítica", autor: "Earl W. Swokoski", estado: "Regular" },
  { titulo: "Contabilidad para no contadores", autor: "Gerardo Guajardo y Nora Andrade", estado: "Bueno" },
  { titulo: "Cálculo Diferencial", autor: "UAEM", estado: "Bueno" },
  { titulo: "Ciencias de la salud", autor: "Bertha Higashida Hirose", estado: "Bueno" },
  { titulo: "Cuento mágico arma y juega “la bella durmiente”", autor: "Navneet Publications", estado: "Regular" },
  { titulo: "Cuentos con escalofríos", autor: "Hernán Carreras", estado: "Bueno" },
  { titulo: "Cuentos con escalofríos", autor: "Hernán Carreras", estado: "Bueno" },
  { titulo: "Cuentos con hadas", autor: "Adriana Ballesteros", estado: "Bueno" },
  { titulo: "Ciencias de la salud II", autor: "Evelia Murillo Gutiérrez y Maribel Yanet Alonso Alonso", estado: "Bueno" },
  { titulo: "Ciencias de la salud 1", autor: "María Guadalupe de Haro Cruz", estado: "Bueno" },
  { titulo: "Diccionario", autor: "Davison y M.", estado: "Regular" },
  { titulo: "De piel de víbora", autor: "Patricia Rodríguez", estado: "Bueno" },
  { titulo: "Documentos Básicos", autor: "Arturo Mantiel Rojas", estado: "Bueno" },
  { titulo: "Derecho penal", autor: "Francesco Carrana", estado: "Bueno" },
  { titulo: "Diccionario Ingles – Español", autor: "Océano", estado: "Bueno" },
  { titulo: "Diccionario Ingles – Español", autor: "Océano", estado: "Bueno" },
  { titulo: "Diccionario Ingles – Español", autor: "Océano", estado: "Bueno" },
  { titulo: "Diccionario jaz de matemáticas", autor: "Direct Libros", estado: "Bueno" },
  { titulo: "Diccionario Escolar", autor: "Larousse", estado: "Regular" },
  { titulo: "Edipo rey", autor: "Sófocles", estado: "Bueno" },
  { titulo: "El principito", autor: "Antonie de Saint-Exupéry", estado: "Bueno" },
  { titulo: "El laberinto de la soledad", autor: "Octavio Paz", estado: "Bueno" },
  { titulo: "El secreto", autor: "R.H.O", estado: "Bueno" },
  { titulo: "En busca de Jim", autor: "Robint F. Brancato", estado: "Bueno" },
  { titulo: "¡Escapa, Chris!", autor: "Roca", estado: "Bueno" },
  { titulo: "El vendedor más grande del mundo", autor: "06 Mandino", estado: "Bueno" },
  { titulo: "El pariente sarniento", autor: "Felipe Garrido", estado: "Bueno" },
  { titulo: "El pariente sarniento", autor: "Felipe Garrido", estado: "Bueno" },
  { titulo: "El pariente sarniento", autor: "Felipe Garrido", estado: "Bueno" },
  { titulo: "El problema de Campanita", autor: "Kiki Tharphe", estado: "Regular" },
  { titulo: "El príncipe", autor: "Nicolás Maquiavelo", estado: "Bueno" },
  { titulo: "Elisa", autor: "C. Gómez", estado: "Bueno" },
  { titulo: "Enzimoterapia", autor: "Karl Ransberger, Héctor Solórzano del Río", estado: "Bueno" },
  { titulo: "Ética", autor: "Adolfo Sánchez", estado: "Bueno" },
  { titulo: "Etimologías", autor: "Esteban Ortega Pedraza", estado: "Bueno" },
  { titulo: "Economía", autor: "Robert I. Heibroner y Lester C. Thurow", estado: "Bueno" },
  { titulo: "Etimologías Grecolatinas", autor: "Jorge Barragán", estado: "Bueno" },
  { titulo: "Examen para ingreso a las universidades", autor: "Colegio Nacional de Matemática", estado: "Bueno" },
  { titulo: "El caballo de la armadura oxidada", autor: "Robert Fisher", estado: "Bueno" },
  { titulo: "Fisica de imágenes", autor: "Francisco Noreña Villarias", estado: "Malo" },
  { titulo: "Fundamentos de enfermería edición III", autor: "Susana Rosales Barrera y Eva Reyes Gómez", estado: "Bueno" },
  { titulo: "Gramática Practica", autor: "Oceanía", estado: "Bueno" },
    { titulo: "Grandes", autor: "Pablo Morales Arguino", estado: "Bueno" },
  { titulo: "Historia verdadera de la conquista de España", autor: "Bernal Díaz del Castillo", estado: "Bueno" },
  { titulo: "Haciendo figuras de plastilina", autor: "Curso en DVD", estado: "Bueno" },
  { titulo: "Haciendo cojines", autor: "Curso en DVD", estado: "Bueno" },
  { titulo: "Haciendo figuras de arcilla", autor: "Curso en DVD", estado: "Bueno" },
  { titulo: "Haciendo magia", autor: "Curso en DVD", estado: "Bueno" },
  { titulo: "Haciendo títeres de dedo", autor: "Curso en DVD", estado: "Bueno" },
  { titulo: "Historia de México 2", autor: "Francisco González Gómez", estado: "Bueno" },
  { titulo: "Haciendo disfraces", autor: "Curso en DVD", estado: "Bueno" },
  { titulo: "Juárez republicano", autor: "Josefina Zoraida Vázquez", estado: "Bueno" },
  { titulo: "Juárez republicano", autor: "Josefina Zoraida Vázquez", estado: "Bueno" },
  { titulo: "Juárez republicano", autor: "Josefina Zoraida Vázquez", estado: "Bueno" },
  { titulo: "Juárez republicano", autor: "Josefina Zoraida Vázquez", estado: "Bueno" },
  { titulo: "Juárez republicano", autor: "Josefina Zoraida Vázquez", estado: "Bueno" },
  { titulo: "Juárez republicano", autor: "Josefina Zoraida Vázquez", estado: "Bueno" },
  { titulo: "Juárez republicano", autor: "Josefina Zoraida Vázquez", estado: "Bueno" },
  { titulo: "Juan Rulfo", autor: "Pedro Páramo", estado: "Bueno" },
   { titulo: "Los ojos de abajo", autor: "María Azuela", estado: "Bueno" },
  { titulo: "La tumba", autor: "José Agustín", estado: "Bueno" },
  { titulo: "La tumba", autor: "José Agustín", estado: "Bueno" },
  { titulo: "Los ladrones del santo grial", autor: "Renato Gionovalli", estado: "Bueno" },
  { titulo: "Los 4 amigos de siempre", autor: "Gilberto Rendón Ortiz", estado: "Bueno" },
  { titulo: "La tumba", autor: "José Agustín", estado: "Bueno" },
  { titulo: "Las batallas en el desierto", autor: "José Emilio Pacheco", estado: "Bueno" },
  { titulo: "La tumba", autor: "José Agustín", estado: "Bueno" },
  { titulo: "Juan Rulfo", autor: "Pedro Páramo", estado: "Bueno" },
  { titulo: "Los ojos de abajo", autor: "María Azuela", estado: "Bueno" },
  { titulo: "Libros selectos", autor: "Reader Digest", estado: "Bueno" },
  { titulo: "Lineamentos elementales de derecho penal", autor: "Fernando Castellanos", estado: "Bueno" },
  { titulo: "La dama de los perros", autor: "María Eugenia Leefmans", estado: "Bueno" },
  { titulo: "Los niños expresan valores", autor: "Educación", estado: "Bueno" },
  { titulo: "La suerte de la conserje", autor: "Sara Sefchovich", estado: "Bueno" },
  { titulo: "La triste historia", autor: "Emma Cárdenas", estado: "Bueno" },
  { titulo: "La ciudad de los transportes", autor: "Olivia Brookes", estado: "Bueno" },
  { titulo: "El secreto de México", autor: "José Antonio Ortega", estado: "Bueno" },
  { titulo: "La tierra el planeta en que vivimos", autor: "Guía Visual", estado: "Bueno" },
  { titulo: "Museo regional", autor: "Consejo Nacional para la Cultura y Artes", estado: "Bueno" },
  { titulo: "Modernas estrategias de enseñanza", autor: "Euro México", estado: "Bueno" },
  { titulo: "Manual de psicología", autor: "Euro México", estado: "Bueno" },
  { titulo: "Manual de usuario", autor: "MS-DOS", estado: "Bueno" },
  { titulo: "Mi mundo de día a día", autor: "Olivia Brookes", estado: "Bueno" },
  { titulo: "Método interactivo del estudiante", autor: "Grupo Océano", estado: "Bueno" },
  { titulo: "Mi libro mágico", autor: "Carmen Espinosa Elenes de Álvarez", estado: "Bueno" },
  { titulo: "Matemáticas 3", autor: "Santiago Valiente Balderas", estado: "Bueno" },
  { titulo: "Matemáticas en contexto 2", autor: "Guillermina Waldegg", estado: "Bueno" },
  { titulo: "Método interactivo del estudiante", autor: "Grupo Océano", estado: "Bueno" },
  { titulo: "Método interactivo del estudiante", autor: "Grupo Océano", estado: "Bueno" },
  { titulo: "Método interactivo del estudiante", autor: "Grupo Océano", estado: "Bueno" },
  { titulo: "Mi mundo de día a día", autor: "Olivia Brookes", estado: "Bueno" },
  { titulo: "Narco traficante para inocentes", autor: "El Fisgón", estado: "Bueno" },
  { titulo: "Nociones de derecho", autor: "UAEM", estado: "Bueno" },
  { titulo: "Nueva legislación de amparo reformada", autor: "Alberto Trueba Urbana y Jorge Trueba Barrera", estado: "Regular" },
  { titulo: "Nudo de víboras", autor: "Francois Mauriac", estado: "Bueno" },
  { titulo: "Nociones de derecho positivo mexicano", autor: "Tomás Velázquez Martines", estado: "Bueno" },
  { titulo: "Nursing", autor: "Tony Grice y James Greenan", estado: "Bueno" },
  { titulo: "Ortografía práctica", autor: "Océano", estado: "Bueno" },
  { titulo: "Orientación educativa", autor: "UAEM", estado: "Bueno" },
  { titulo: "Pintando con crayones y vinilos", autor: "Curso en DVD", estado: "Bueno" },
  { titulo: "Pintando con lápiz de color y ecolin", autor: "Curso en DVD", estado: "Bueno" },
  { titulo: "Precalculus", autor: "Eighth Edition", estado: "Bueno" },
  { titulo: "Psicología", autor: "Charles G. Morris y Albert A. Maisto", estado: "Bueno" },
  { titulo: "Probabilidad y estadística", autor: "Salazar Bahena Martínez", estado: "Bueno" },
  { titulo: "Probabilidad y estadística dinámica", autor: "Luis Martínez Vásquez", estado: "Bueno" },
  { titulo: "Propol vuj: sagrado de los mayos", autor: "Víctor Trejo", estado: "Bueno" },
  { titulo: "PowerPoint", autor: "SEC", estado: "Regular" },
  { titulo: "Perro dog", autor: "David Martín del Campo", estado: "Regular" },
  { titulo: "Para leer en el metro 1", autor: "Carlos Monsiváis", estado: "Bueno" },
  { titulo: "Poder local", autor: "Josefa Carrillo Gómez", estado: "Bueno" },
  { titulo: "Poema", autor: "Del Mío Cid", estado: "Bueno" },
  { titulo: "Peces e invertebrados marinos en su hábitat", autor: "National Geographic", estado: "Bueno" },
  { titulo: "Reptiles y anfibios en sus hábitat", autor: "National Geographic", estado: "Bueno" },
  { titulo: "Reflexiones sobre la no violencia", autor: "Juan María Parent Jacquemin", estado: "Bueno" },
  { titulo: "Relación humana", autor: "Leticia Ordoz Serrano", estado: "Bueno" },
  { titulo: "Rebelión en la granja", autor: "George Orwell", estado: "Bueno" },
  { titulo: "Rebelión en la granja", autor: "George Orwell", estado: "Bueno" },
  { titulo: "Sostenibilidad y desarrollo", autor: "Ignacio Pichardo Pagaza", estado: "Bueno" },
  { titulo: "Santa", autor: "Federico Gamboa", estado: "Bueno" },
  { titulo: "Santa", autor: "Federico Gamboa", estado: "Bueno" },
  { titulo: "Santa", autor: "Federico Gamboa", estado: "Bueno" },
  { titulo: "Santa", autor: "Federico Gamboa", estado: "Bueno" },
  { titulo: "Santa", autor: "Federico Gamboa", estado: "Bueno" },
  { titulo: "Santa", autor: "Federico Gamboa", estado: "Bueno" },
  { titulo: "Santa", autor: "Federico Gamboa", estado: "Bueno" },
  { titulo: "Santa", autor: "Federico Gamboa", estado: "Bueno" },
  { titulo: "Santa", autor: "Federico Gamboa", estado: "Bueno" },
  { titulo: "Third Edition Solutions", autor: "Tim Falla y Paul A. Davies", estado: "Bueno" },
  { titulo: "Tú que intentas volar", autor: "María Eugenia Leefmans", estado: "Bueno" },
  { titulo: "Tiempo de educar tomo 15", autor: "Comité Editorial Interinstitucional", estado: "Bueno" },
  { titulo: "Tiempo de educar tomo 16", autor: "Comité Editorial Interinstitucional", estado: "Bueno" },
  { titulo: "Tiempo de educar tomo 17", autor: "Comité Editorial Interinstitucional", estado: "Bueno" },
  { titulo: "Tiempo de educar tomo 18", autor: "Comité Editorial Interinstitucional", estado: "Bueno" },
  { titulo: "Tiempo de educar tomo 19", autor: "Comité Editorial Interinstitucional", estado: "Bueno" },
  { titulo: "Tiempo de educar tomo 20", autor: "Comité Editorial Interinstitucional", estado: "Bueno" },
  { titulo: "Tiempo de educar tomo 24", autor: "Comité Editorial Interinstitucional", estado: "Bueno" },
  { titulo: "Tablas matemáticas", autor: "Arquímedes", estado: "Regular" },
  { titulo: "Tradiciones del maíz", autor: "Tupperware", estado: "Bueno" },
  { titulo: "Vocabulario científico", autor: "Océano", estado: "Bueno" },
  { titulo: "Yes, we can!", autor: "SEP", estado: "Bueno" },
  { titulo: "Y colorín colorado este cuento no se ha acabado", autor: "Odín Dupeyrón", estado: "Bueno" },
  { titulo: "Yes, we can! 5", autor: "SEP", estado: "Bueno" },
  { titulo: "Zapata", autor: "Luciano Concheiro Borquez", estado: "Bueno" }
];

const select = document.getElementById("titulo");
const autorSpan = document.getElementById("autor");
const estadoSpan = document.getElementById("estado");

// Llenar el select
libros.forEach(libro => {
  const option = document.createElement("option");
  option.value = libro.titulo;
  option.textContent = libro.titulo;
  select.appendChild(option);
});

// Mostrar datos al seleccionar
select.addEventListener("change", function() {
  const seleccionado = libros.find(libro => libro.titulo === this.value);
  if (seleccionado) {
    autorSpan.textContent = seleccionado.autor;
    estadoSpan.textContent = seleccionado.estado;
  } else {
    autorSpan.textContent = "";
    estadoSpan.textContent = "";
  }
});
